### ISSUE TITLE
Overlapping of navigation page and Social's icons

### ISSUE THREAD

**Issue by ShaileshKumar007** [cekit/cekit.io#27]
On the landing page of the website, the Navigation bar and the Socials icons(Twitter, GitHub, etc.) are overlapping with each other.
It'll look good if we shift the navbar at the top and socials at the bottom of the page or we can include the socials also in the navbar.

## Screenshot:
![cekit](https://user-images.githubusercontent.com/71178959/136691800-95e4d8b1-ace9-438c-906e-5b07be185685.JPG)

**Comment by rnc** [comment]
I believe these are working now testing on Chrome and Firefox on Fedora 34
